# fault_translator.py

SCS_FAULT_MAP = {
    0: "NONE - System operational", 1: "WAITING FOR DEVICES", 2: "DEVICES UNINITIALIZED",
    3: "KEY POWER OFF", 4: "SDB2 FAULT", 5: "BIT FAULT", 6: "DIAG FAULT",
    7: "DIAG POST TIMEOUT", 8: "SRC FAILED", 9: "HARDWARE FAULT CONDITION",
    10: "USER REQUESTED", 11: "SUBSYSTEM MISSING", 12: "PASSTHROUGH",
    13: "DCB OFFSET FAILURE", 14: "DARKCAL REQUESTED", 15: "ENCODER COUNT EXCEEDED (Normal)",
    16: "ESTOP", 17: "ILOCK", 18: "HVPS RAMPUP", 19: "STANDBY", 20: "REBOOT",
    21: "WATCHDOG", 22: "SYSTIC FAULT", 23: "ENCODER FAULT", 24: "LIGHT CURTAIN FAULT",
    25: "GALIL FAULT", 26: "ACUVIM FAULT", 27: "YASKAWA FAULT", 28: "MFORCE FAULT",
    29: "UPS FAULT", 30: "HVPS FAULT", 31: "DCB FAULT", 32: "SYSTEM VERIFY FAULT",
    33: "BMS ENTRANCE BAG JAM", 34: "BMS BHS FAULT", 35: "SYSTIC TIMEOUT",
    36: "SDB2 TIMEOUT", 37: "DCB TIMEOUT", 38: "DPP RTR DOWN", 39: "BMS RTR DOWN",
    40: "IAC RTR DOWN", 41: "DPP OPSTATE FAULT", 42: "IAC OPSTATE FAULT",
    43: "INIT TIMEOUT FAULT", 44: "SEASONING FAILED", 45: "TRANSIENTS FAILED",
    46: "ARRAYTESTS FAILED", 47: "BMS SUBSYS MISSING", 48: "IAC SUBSYS MISSING",
    49: "DPP SUBSYS MISSING", 50: "DIAGS SUBSYS MISSING", 51: "PLC CONNECTION LOSS",
    52: "DPP HIGH WATERMARK", 53: "LIGHTCURTAIN CHANGED", 54: "CHILLER FAULT",
    55: "SYSTEMP AMBIENT", 56: "SYSTEMP INLET BOX", 57: "SYSTEM OUTLET BOX",
    58: "SYSTEMP SARCOPHAGUS", 59: "SYSTEMP COMPUTER RACK", 60: "SYSTEMP ENCODER MONITOR"
}

def translate_fault_code(code):
    """Übersetzt einen SCS-Fehlercode in einen lesbaren String."""
    try:
        code_int = int(code)
        return SCS_FAULT_MAP.get(code_int, f"Unbekannter Fehlercode ({code})")
    except (ValueError, TypeError):
        return f"Ungültiger Fehlercode ({code})"